### ISSUE TITLE
runnmf - Missing function

### ISSUE THREAD

**Issue by pbl007** [Leveltlab/SpectralSegmentation#3]
Encountered the following error:

loading...24-Sep-2022 20:06:47
Dimensions : 300  256  256
Frequency :  1
Memory mapped $$$$/Testing_SpectralSegmentation/C_183_baseline_FOV_3_mag_3_L_256px_30hz_UNI_00001_DecTrans.dat
border input was not good (maybe too small, large or nan)
saved the spar into current folder
iteration  1/27: Undefined function 'runnmf' for input arguments of type 'double'.

Error in PixelCor (line 150)
        [W, H] = runnmf(Sig, lx, size(V));

Error in roisfromlocalmax (line 152)
                        [NwCon, NwA, NwF, NwV, Ro, Rvar] = PixelCor(size(Mask), F, sbxt, py,
                        px, Iy, Ix, yrange, xrange, cutOffCorr);

Error in getSpectrois (line 144)
    [PP, Mask, SpatialCorr, rlog] = roisfromlocalmax(Img, PP, Mask, spar, sbxt, freq,
    SpatialCorr);

Error in SpectralPipeline (line 51)
getSpectrois

**Comment by pbl007** [comment]
All requirements added to Matlab Path as instructed.
Thanks!

**Comment by Leanderrr** [comment]
I see, we'll fix this!

**Comment by chrisvdt** [comment]
This should now be resolved, the section with this function should be commented, it is only for debugging.
