### ISSUE TITLE
memory function is platform dependent (Windows only)

### ISSUE THREAD

**Issue by pbl007** [Leveltlab/SpectralSegmentation#4]
Hi

On DecimateTrans.m, the use of `memory` is platform dependent and only works on windows. I couldn't find a good replacement on OSX / Linux so a crude workaround until this is made into an input [or `global`] parameter.

%memory function is for windows - Hardoded value for others.... PB
if ~isunix
    [~, memSize] = memory;
    memSize = memSize.PhysicalMemory.Available ./ (1*10^9);
    memSize = max(2, memSize); % Do not accept less than 2GB memory
else
    memSize = 8; %HARDCOCED
end

**Comment by chrisvdt** [comment]
Hi,

Thanks for the info, we should have a look into this.

From: Pablo Blinder ***@***.***>
Sent: Tuesday, 11 October 2022 22:41
To: Leveltlab/SpectralSegmentation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Leveltlab/SpectralSegmentation] memory function is platform dependent (Windows only) (Issue #4)


Hi

On DecimateTrans.m, the use of memory is platform dependent and only works on windows. I couldn't find a good replacement on OSX / Linux so a crude workaround until this is made into an input [or global] parameter.

%memory function is for windows - Hardoded value for others.... PB
if isunix
[, memSize] = memory;
memSize = memSize.PhysicalMemory.Available ./ (1*10^9);
memSize = max(2, memSize); % Do not accept less than 2GB memory
else
memSize = 8; %HARDCOCED
end

-

**Comment by Leanderrr** [comment]
Hi,

Thank you for the proposed change, we have implemented that one!

kind regards,
Leander
